# Default values for Mas webapp. https://github.com/SocialGouv/helm-charts/blob/master/charts/webapp/values.yaml
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
---
image:
  repository: $CI_REGISTRY_IMAGE
  tag: master

deployment:
  imagePullSecrets:
    - name: regcred

  resources:
    limits:
      cpu: 1000m
      memory: 256Mi
    requests:
      cpu: 5m
      memory: 64Mi

  livenessProbe:
    initialDelaySeconds: 30
    path: /health
    periodSeconds: 15
  readinessProbe:
    initialDelaySeconds: 30
    path: /health
    periodSeconds: 15

  env:
    - name: PRODUCTION
      value: "${PRODUCTION}"
    - name: PGSSLMODE
      value: "require"
    - name: HASURA_URL
      value: "http://hasura-carnets/v1/graphql"
  envFrom:
    - secretRef:
        name: carnets-secrets

ingress:
  enabled: true
  annotations:
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/ingress.class: "azure/application-gateway"
  hosts:
    - host: carnets.fabrique.social.gouv.fr
      paths:
        - path: /
          servicePort: 3000

  tls:
    - hosts:
        - carnets.fabrique.social.gouv.fr
      secretName: carnets-crt
