image:
  repository: $CI_REGISTRY_IMAGE/hasura
  tag: master

deployment:
  imagePullSecrets:
    - name: regcred

  livenessProbe:
    path: /healthz
    initialDelaySeconds: 30
    periodSeconds: 20
  readinessProbe:
    path: /healthz
    initialDelaySeconds: 30
    periodSeconds: 20

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 1024Mi

  env:
    - name: NODE_ENV
      value: "production"
    - name: HASURA_GRAPHQL_ENABLE_CONSOLE
      value: "true"
    - name: HASURA_GRAPHQL_SERVER_PORT
      value: "80"
    - name: HASURA_GRAPHQL_ENABLED_LOG_TYPES
      value: "startup, http-log, webhook-log, websocket-log, query-log"
    - name: HASURA_GRAPHQL_NO_OF_RETRIES
      value: "5"
    - name: HASURA_GRAPHQL_UNAUTHORIZED_ROLE
      value: "anonymous"
  envFrom:
    - secretRef:
        name: carnets-secrets
# ingress:
#   enabled: false
ingress:
  enabled: true
  annotations:
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/ingress.class: "azure/application-gateway"
  hosts:
    - host: "hasura-carnets.dev.fabrique.social.gouv.fr"
      paths:
        - path: /
          servicePort: "80"

  tls:
    - hosts:
        - "hasura-carnets.dev.fabrique.social.gouv.fr"
      secretName: wildcard-crt
