image:
  repository: $CI_REGISTRY_IMAGE/hasura
  tag: master

labels:
  app.kubernetes.io/part-of: carnets
  owner: carnets
  team: carnets

deployment:
  annotations:
    app.gitlab.com/app: ${CI_PROJECT_PATH_SLUG}
    app.gitlab.com/env: ${CI_ENVIRONMENT_SLUG}

  livenessProbe:
    periodSeconds: 20
  readinessProbe:
    periodSeconds: 20

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 1000m
      memory: 1024Mi

  env:
    - name: NODE_ENV
      value: "production"
    - name: HASURA_GRAPHQL_DATABASE_URL
      value: "${HASURA_GRAPHQL_DATABASE_URL}"
    - name: HASURA_GRAPHQL_ENABLE_CONSOLE
      value: "false"
    - name: HASURA_GRAPHQL_ADMIN_SECRET
      value: "${HASURA_GRAPHQL_ADMIN_SECRET}"
    - name: HASURA_GRAPHQL_SERVER_PORT
      value: "80"
    - name: HASURA_GRAPHQL_ENABLED_LOG_TYPES
      value: "startup, http-log, webhook-log, websocket-log, query-log"

ingress:
  enabled: true
  annotations:
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/ingress.class: "azure/application-gateway"
  hosts:
    - host: "hasura-carnets.dev.fabrique.social.gouv.fr"
      paths:
        - path: /
          servicePort: "80"

  tls:
    - hosts:
        - "hasura-carnets.dev.fabrique.social.gouv.fr"
      secretName: wildcard-crt
