include:
  - project: SocialGouv/gitlab-ci-yml
    file: /autodevops.yml
    ref: v17.3.1

variables:
  AUTO_DEVOPS_RELEASE_AUTO: "YEAH"
  AUTO_DEVOPS_PRODUCTION_AUTO: "🚀"

Lint:
  rules:
    - when: never

Test:
  rules:
    - when: never

Register image:
  extends: .autodevops_register_image
  variables:
    DOCKER_BUILD_ARGS: >-
      --shm-size 512M
    IMAGE_NAME: $CI_REGISTRY_IMAGE/app

Register image Hasura:
  extends: .autodevops_register_image
  dependencies: []
  needs: []
  environment:
    name: ${CI_COMMIT_REF_NAME}-dev2
  variables:
    CONTEXT: ./packages/hasura
    IMAGE_NAME: $CI_REGISTRY_IMAGE/hasura
