include:
  - project: SocialGouv/gitlab-ci-yml
    file: /autodevops.yml
    ref: v22.1.9

stages:
  - Install
  - Code Quality
  - Registration
  - Release
  - Deploy
  - Wait
  - Seed

variables:
  AUTO_DEVOPS_KANIKO: "pouet"
  AUTO_DEVOPS_RELEASE_AUTO: "🔖"
  AUTO_DEVOPS_ENABLE_KAPP: "plop"

Register hasura image:
  extends: .autodevops_register_kaniko_image
  dependencies: []
  needs: []
  variables:
    DOCKER_BUILD_ARGS: >-
      --dockerfile=packages/hasura/Dockerfile
    CONTEXT: packages/hasura
    IMAGE_NAME: carnets-hasura

.e2e_tests:
  environment:
    name: ${CI_COMMIT_REF_NAME}-dev2
    url: https://${CI_ENVIRONMENT_SLUG}-${CI_PROJECT_NAME}.${KUBE_INGRESS_BASE_DOMAIN}
  only:
    refs:
      - branches
  except:
    refs:
      - master
    variables:
      # Don't run when deploying in production or releasing
      - $PRODUCTION
      - $RELEASE

Wait hasura:
  stage: Wait
  allow_failure: true
  extends: .e2e_tests
  image:
    name: registry.gitlab.factory.social.gouv.fr/socialgouv/docker/azure-db:1.18.0
    entrypoint: [""]
  script:
    - kubectl rollout status deployment.v1.apps/hasura

Create seeds DB (dev):
  stage: Seed
  extends: .e2e_tests
  allow_failure: true
  image:
    name: postgres:11
    entrypoint: [""]
  variables:
    GIT_STRATEGY: clone
    PGHOST: carnetsdevserver.postgres.database.azure.com
    PGUSER: user_${CI_COMMIT_SHORT_SHA}@${PGHOST}
    PGPASSWORD: password_${CI_COMMIT_SHORT_SHA}
    PGDATABASE: autodevops_${CI_COMMIT_SHORT_SHA}
    PGSSLMODE: require
  script:
    - psql < ./scripts/seeds-dev.sql
