---
apiVersion: v1
kind: Pod
metadata:
  name: rss-site
  namespace: carnets-test1
  labels:
    app: web
spec:
  containers:
    - name: pod1
      image: nginx
      ports:
        - containerPort: 80
