jobs:
  runs:
    create-db:
      use: SocialGouv/kontinuous/plugins/contrib/jobs/create-db
      with:
        pgAdminSecretRefName: pg-scaleway
    seed-db:
      use: SocialGouv/kontinuous/plugins/contrib/jobs/seed-db
      ~needs: [hasura]
      with:
        seedPath: scripts/seeds-dev.sql

hasura:
  ~needs: [create-db]
  envFrom:
  - secretRef:
      name: hasura-configmap
  - secretRef:
      name: hasura-sealed-secret

app:
  envFrom:
  - secretRef:
      name: carnets-configmap
  - secretRef:
      name: app-sealed-secrets
