seeds:
  ~chart: jobs
  runs:
    seed-db:
      use: seed-db
      ~needs: [hasura]
      with:
        seedPath: scripts/seeds.sql
      envFrom:
        - secretRef:
            name: pg-app

app:
  vars:
    ENV: review
