seeds:
  ~chart: jobs
  runs:
    seed-db:
      use: seed-db
      ~needs: [hasura]
      with:
        seedPath: scripts/seeds.sql
      envFrom:
        - secretRef:
            name: pg-app

hasura:
  envFrom:
  - secretRef:
      name: pg-app
  - configMapRef:
      name: hasura
  - secretRef:
      name: hasura
  - secretRef:
      name: "{{ .Values.global.pgSecretName }}"

app:
  vars:
    ENV: review
  envFrom:
  - configMapRef:
      name: app
  - secretRef:
      name: app
