database:
  ~chart: jobs
  ~chart-group: deploy
  runs:
    create-db:
      use: SocialGouv/kontinuous/plugins/contrib/jobs/create-db
      with:
        pgAdminSecretRefName: pg-scaleway
    seed-db:
      use: SocialGouv/kontinuous/plugins/contrib/jobs/seed-db
      needs: [hasura]
      with:
        seedPath: scripts/seeds-dev.sql

hasura:
  ~needs: [create-db]
  envFrom:
  - configMapRef:
      name: hasura-configmap
  - secretRef:
      name: hasura-sealed-secrets
  - secretRef:
      name: "{{ .Values.global.pgSecretName }}"

app:
  envFrom:
  - configMapRef:
      name: carnets-configmap
  - secretRef:
      name: app-sealed-secrets
