database:
  ~chart: jobs
  runs:
    create-db:
      use: create-db
    seed-db:
      use: seed-db
      ~needs: [hasura]
      with:
        seedPath: scripts/seeds-dev.sql

hasura:
  ~needs: [create-db]
  envFrom:
  - configMapRef:
      name: hasura
  - secretRef:
      name: hasura
  - secretRef:
      name: "{{ .Values.global.pgSecretName }}"

app:
  vars:
    ENV: review
  envFrom:
  - configMapRef:
      name: app
  - secretRef:
      name: app
