app:
  labels:
    oblik.socialgouv.io/enabled: "true"
  annotations:
    oblik.socialgouv.io/request-apply-target: "peak"
    oblik.socialgouv.io/increase-request-cpu-algo: "ratio"
    oblik.socialgouv.io/increase-request-cpu-value: "0.1"
    oblik.socialgouv.io/increase-request-memory-algo: "ratio"
    oblik.socialgouv.io/increase-request-memory-value: "0.1"
  host: "{{ .Values.global.host }}"
  vars:
    NEXTAUTH_URL: https://{{ .Values.global.host }}

hasura:
  labels:
    oblik.socialgouv.io/enabled: "true"
  annotations:
    oblik.socialgouv.io/request-apply-target: "peak"
    oblik.socialgouv.io/increase-request-cpu-algo: "ratio"
    oblik.socialgouv.io/increase-request-cpu-value: "0.1"
    oblik.socialgouv.io/increase-request-memory-algo: "ratio"
    oblik.socialgouv.io/increase-request-memory-value: "0.1"
  host: hasura-{{ .Values.global.host }}
  startupProbe:
    initialDelaySeconds: 300

pg:
  cnpg-cluster:
    backup:
      barmanObjectStore:
        ~tpl~destinationPath: "s3://fabrique-prod-backups/carnets-preprod"
        s3Credentials:
          accessKeyId:
            ~tpl~name: fabrique-prod-backups-access-key
            key: bucket_access_key
          secretAccessKey:
            ~tpl~name: fabrique-prod-backups-access-key
            key: bucket_secret_key
          region:
            ~tpl~name: fabrique-prod-backups-access-key
            key: bucket_region
    resources:
      requests:
        memory: 1Gi
      limits:
        cpu: "1"
        memory: 1Gi

jobs:
  runs:
    build-app:
      with:
        buildArgs:
          NEXT_PUBLIC_MATOMO_SITE_ID: "24"
          NEXT_PUBLIC_MATOMO_URL: "https://matomo.fabrique.social.gouv.fr/"
          NEXT_PUBLIC_HASURA_URL:
            "https://hasura-{{ .Values.global.host }}/v1/graphql"
