app:
  host: {{ .Values.global.host }}
  vars:
    NEXTAUTH_URL: https://{{ .Values.global.host }}

hasura:
  host: hasura-{{ .Values.global.host }}

jobs:
  runs:
    build-app:
      with:
        buildArgs:
          NEXT_PUBLIC_HASURA_URL: "https://hasura-{{ .Values.global.host }}/v1/graphql"
