app:
  host: new-{{ .Values.global.host }}
  vars:
    NEXTAUTH_URL: https://new-{{ .Values.global.host }}
hasura:
  host: new-hasura-{{ .Values.global.host }}
jobs:
  runs:
    build-app:
      with:
        buildArgs:
          HASURA_URL: "http://hasura:8080/v1/graphql"
          NEXT_PUBLIC_HASURA_URL: "https://new-hasura-{{ .Values.global.host }}/v1/graphql"
