app:
  annotations:
    oblik.socialgouv.io/enabled: "true"
  host: { { .Values.global.host } }
  vars:
    NEXTAUTH_URL: https://{{ .Values.global.host }}

hasura:
  annotations:
    oblik.socialgouv.io/enabled: "true"
  host: hasura-{{ .Values.global.host }}
  startupProbe:
    initialDelaySeconds: 300

pg:
  cnpg-cluster:
    resources:
      requests:
        memory: 1Gi
      limits:
        cpu: "1"
        memory: 1Gi

jobs:
  runs:
    build-app:
      with:
        buildArgs:
          NEXT_PUBLIC_MATOMO_SITE_ID: "24"
          NEXT_PUBLIC_MATOMO_URL: "https://matomo.fabrique.social.gouv.fr/"
          NEXT_PUBLIC_HASURA_URL:
            "https://hasura-{{ .Values.global.host }}/v1/graphql"
