pg:
  cnpg-cluster:
    backup:
      barmanObjectStore:
        ~tpl~destinationPath: "s3://fabrique-dev-backups/carnets-preprod"
        s3Credentials:
          accessKeyId:
            ~tpl~name: fabrique-dev-backups-access-key
            key: bucket_access_key
          secretAccessKey:
            ~tpl~name: fabrique-dev-backups-access-key
            key: bucket_secret_key
          region:
            ~tpl~name: fabrique-dev-backups-access-key
            key: bucket_region

seeds:
  ~chart: jobs
  runs:
    seed-db:
      use: seed-db
      ~needs: [hasura]
      with:
        seedPath: scripts/seeds.sql
      envFrom:
        - secretRef:
            name: pg-app

app:
  vars:
    ENV: preprod
