app:
  enabled: true
  imagePackage: app
  probesPath: /healthz
  env:
    - name: APP_URL
      value: https://{{ .Values.global.host }}
    - name: HASURA_URL
      value: https://hasura-{{ .Values.global.host }}/v1/graphql
  envFrom:
    - secretRef:
        name: carnets-sealed-secret
    - configMap:
        name: carnets-configmap
  ingress:
    annotations:
      nginx.ingress.kubernetes.io/configuration-snippet: |
        more_set_headers "X-Frame-Options: deny";
        more_set_headers "X-XSS-Protection: 1; mode=block";
        more_set_headers "X-Content-Type-Options: nosniff";

hasura:
  enabled: true
  containerPort: 80
  envFrom:
    - secretRef:
        name: hasura-sealed-secret
    - configMapRef:
        name: hasura-configmap