projectName: fabrique

dependencies:
  fabrique:
    patches:
      setUndefinedStorageClassnameCnpg:
        options:
          defaultStorageClassName: csi-cinder-high-speed
    dependencies:
      contrib:
        preDeploy:
          importSecrets:
            options:
              secrets:
                carnets-dev-backups-access-key:
                carnets-prod-backups-access-key:
    extends:
      - name: ovh
      - name: buildkit-service
