app:
  ~chart: app
  ~needs: [build-app]
  probesPath: /healthz
  imagePackage: app
  envFrom:
  - configMapRef:
      name: carnets-configmap

hasura:
  ~chart: hasura
  ~needs: [build-hasura]
  imagePackage: hasura
  envFrom:
  - configMapRef:
      name: hasura-configmap
  - secretRef:
      name: "{{ .Values.global.pgSecretName }}"

jobs:
  ~chart: jobs
  runs:
    build-app:
      use: build
      memoryLimit: 8Gi
      with:
        imagePackage: app
        buildArgs:
          NEXT_PUBLIC_HASURA_URL: "https://hasura-{{ .Values.global.host }}/v1/graphql"

    build-hasura:
      use: build
      with:
        imagePackage: hasura
        context: packages/hasura
