app:
  ~chart: app
  ~needs: [build-app]
  probesPath: /healthz
  imagePackage: app
  envFrom:
  - configMapRef:
      name: app
  vars:
    NEXTAUTH_URL: https://{{ .Values.global.host }}
  securityContext:
    fsGroup: 1000
    runAsUser: 1000
    runAsGroup: 1000

pg:
  ~chart: pg

hasura:
  ~chart: hasura
  ~needs: [build-hasura, pg]
  imagePackage: hasura
  envFrom:
  - configMapRef:
      name: hasura
  - secretRef:
      name: "{{ .Values.global.pgSecretName }}"
  securityContext:
    fsGroup: 1001
    runAsUser: 1001
    runAsGroup: 1001

jobs:
  ~chart: jobs
  runs:
    build-app:
      use: build
      memoryLimit: 8Gi
      with:
        imagePackage: app
        buildArgs:
          NEXT_PUBLIC_HASURA_URL: "https://hasura-{{ .Values.global.host }}/v1/graphql"
    build-hasura:
      use: build
      with:
        imagePackage: hasura
        context: packages/hasura
