app:
  ~chart: app
  ~needs: [build-app]
  probesPath: /api/healthz
  imagePackage: app
  envFrom:
    - secretRef:
        name: app
  vars:
    ENV: prod
    HASURA_URL: http://hasura/v1/graphql
    NEXTAUTH_URL: https://{{ .Values.global.host }}
  securityContext:
    fsGroup: 1000
    runAsUser: 1000
    runAsGroup: 1000

pg:
  ~chart: pg

hasura:
  ~chart: hasura
  ~needs: [build-hasura, pg]
  imagePackage: hasura
  annotations:
    "oblik.socialgouv.io/min-request-memory": 1Gi
    "oblik.socialgouv.io/min-request-cpu": 300m
  envFrom:
    - secretRef:
        name: pg-app
    - configMapRef:
        name: hasura
    - secretRef:
        name: hasura
  securityContext:
    fsGroup: 1001
    runAsUser: 1001
    runAsGroup: 1001
  startupProbe:
    initialDelaySeconds: 120
    httpGet:
      path: /healthz
      port: http
    failureThreshold: 10
    periodSeconds: 20

jobs:
  ~chart: jobs
  runs:
    build-app:
      use: build
      memoryLimit: 8Gi
      with:
        imagePackage: app
        buildArgs:
          NEXT_PUBLIC_HASURA_URL:
            "https://hasura-{{ .Values.global.host }}/v1/graphql"
        secrets:
          sentry_auth_token:
            secretName: app
            secretKey: SENTRY_AUTH_TOKEN
    build-hasura:
      use: build
      with:
        imagePackage: hasura
        context: packages/hasura
