app:
  ~chart: app
  ~chart-group: deploy
  probesPath: /healthz
  imagePackage: app
  envFrom:
  - configMapRef:
      name: carnets-configmap

hasura:
  ~chart: hasura
  ~chart-group: deploy
  imagePackage: hasura
  envFrom:
  - configMapRef:
      name: hasura-configmap
  - secretRef:
      name: "{{ .Values.global.pgSecretName }}"

build-app:
  ~chart: jobs
  runs:
    build:
      use: build
      memoryLimit: 8Gi
      memoryRequest: 4Gi
      with:
        imagePackage: app
        buildArgs:
          NEXT_PUBLIC_HASURA_URL: "https://hasura-{{ .Values.global.host }}/v1/graphql"

build-hasura:
  ~chart: jobs
  runs:
    build:
      use: build
      with:
        imagePackage: hasura
        context: packages/hasura