name: Kontinuous
on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "v*"

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.event.ref }}

jobs:

  build-app:
    runs-on: ubuntu-latest
    steps:
      - name: build application
        uses: SocialGouv/kontinuous/.github/actions/deploy-via-webhook@v1
        with:
          chart: build-app
          token: ${{ secrets.GITHUB_TOKEN }}
          webhookToken: ${{ secrets.KUBEWEBHOOK_TOKEN }}
  
  build-hasura:
    runs-on: ubuntu-latest
    steps:
      - name: build hasura
        uses: SocialGouv/kontinuous/.github/actions/deploy-via-webhook@v1
        with:
          chart: build-hasura
          token: ${{ secrets.GITHUB_TOKEN }}
          webhookToken: ${{ secrets.KUBEWEBHOOK_TOKEN }}

  deploy:
    needs: [build-app, build-hasura]
    uses: SocialGouv/kontinuous/.github/workflows/workflow-webhook.yaml@v1
    secrets: inherit
    with:
      chart: deploy
