name: Kontinuous
on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "v*"

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.event.ref }}

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: build
        uses: SocialGouv/kontinuous/.github/actions/deploy-via-webhook@v1
        with:
          chart: build
          triggerWebhook: true
          ignoreProjectTemplates: true
          token: ${{ secrets.GITHUB_TOKEN }}
          webhookToken: ${{ secrets.KUBEWEBHOOK_TOKEN }}

  deploy:
    needs: [build]
    uses: SocialGouv/kontinuous/.github/workflows/workflow-webhook.yaml@v1
    secrets: inherit
    with:
      chart: deploy
      triggerWebhook: true
