name: Production

on:
  push:
    tags:
      - v*

concurrency:
  group: production
  cancel-in-progress: true

jobs:

  ##############################################################################
  ## BUILD AND REGISTER APPLICATION IMAGE
  ##############################################################################
  register:
    name: Build & Register application
    runs-on: ubuntu-latest
    steps:

    - name: Get project name
      run: |
        echo "project=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV

    - name: Use autodevops build and register
      uses: SocialGouv/actions/autodevops-build-register@v1
      with:
        environment: prod
        imageName: fabrique/carnets
        project: ${{ env.project }}
        token: ${{ secrets.GITHUB_TOKEN }}

  ##############################################################################
  ## BUILD AND REGISTER HASURA IMAGE
  ##############################################################################
  register-hasura:
    name: Build & Register Hasura
    runs-on: ubuntu-latest
    steps:

    - name: Get project name
      run: |
        echo "project=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV

    - name: Use autodevops build and register
      uses: SocialGouv/actions/autodevops-build-register@v1
      with:
        environment: prod
        imageName: fabrique/hasura
        project: ${{ env.project }}
        token: ${{ secrets.GITHUB_TOKEN }}
        dockerfile: ./packages/hasura/Dockerfile

  ##############################################################################
  ## DEPLOY PRODUCTION APPLICATION
  ##############################################################################
  deploy:
    name: Deploy production
    runs-on: ubuntu-latest
    needs: [register, register-hasura]
    environment:
      name: production
      url: ${{ steps.deploy.outputs.url }}
    steps:

    - name: Use autodevops manifests generation
      uses: SocialGouv/actions/autodevops-manifests@v1
      with:
        environment: prod
        rancherId: ${{ secrets.RANCHER_PROJECT_ID }}
        socialgouvBaseDomain: ${{ secrets.SOCIALGOUV_BASE_DOMAIN }}
        pgUserSecretPrefix: pg-user

    - name: Use autodevops deployment
      uses: SocialGouv/actions/autodevops-deploy@v1
      id: deploy
      with:
        environment: prod
        token: ${{ secrets.GITHUB_TOKEN }}
        kubeconfig: ${{ secrets.KUBECONFIG }}
        rancherId: ${{ secrets.RANCHER_PROJECT_ID }}
