name: Production

on:
  push:
    tags:
      - v*

concurrency:
  group: production
  cancel-in-progress: true

jobs:
  register-app:
    name: Build & Register application
    runs-on: ubuntu-latest
    steps:
    - name: Use autodevops build and register
      uses: SocialGouv/actions/autodevops-build-register@v1
      with:
        environment: prod
        imagePackage: app
        token: ${{ secrets.GITHUB_TOKEN }}

  register-hasura:
    name: Build & Register Hasura
    runs-on: ubuntu-latest
    steps:
    - name: Use autodevops build and register
      uses: SocialGouv/actions/autodevops-build-register@v1
      with:
        environment: prod
        imagePackage: hasura
        dockerfile: ./packages/hasura/Dockerfile
        token: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    name: Deploy application
    runs-on: ubuntu-latest
    needs: [register-app, register-hasura]
    environment:
      name: production
      url: https://carnets.fabrique.social.gouv.fr
    steps:
    - name: Use kube-workflow deployment
      uses: SocialGouv/kube-workflow@v1
      with:
        environment: prod
        token: ${{ secrets.GITHUB_TOKEN }}
        kubeconfig: ${{ secrets.KUBECONFIG }}
        rancherProjectId: ${{ secrets.RANCHER_PROJECT_ID }}
        rancherProjectName: ${{ secrets.RANCHER_PROJECT_NAME }}
