name: Review

on:
  push:
    branches:
      - beta
    tags-ignore:
      - v*

concurrency:
  cancel-in-progress: true
  group: review-${{ github.ref }}

jobs:

  create-db:
    name: Create postgres database
    runs-on: ubuntu-latest
    steps:

    - uses: SocialGouv/actions/autodevops-create-db@v1
      with:
        environment: dev
        kubeconfig: ${{ secrets.KUBECONFIG }}
        rancherId: ${{ secrets.RANCHER_PROJECT_ID }}
        socialgouvBaseDomain: ${{ secrets.SOCIALGOUV_BASE_DOMAIN }}

  ##############################################################################
  ## BUILD AND REGISTER HASURA IMAGE
  ##############################################################################
  register-hasura:
    name: Build & Register Hasura
    runs-on: ubuntu-latest
    steps:

    - name: Get project name
      run: |
        echo "project=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV

    - name: Use autodevops build and register
      uses: SocialGouv/actions/autodevops-build-register@v1
      with:
        imageName: fabrique/hasura
        project: ${{ env.project }}
        token: ${{ secrets.GITHUB_TOKEN }}
        dockercontext: ./packages/hasura
        dockerfile: ./packages/hasura/Dockerfile

  ##############################################################################
  ## GENERATE HASURA MANIFESTS
  ##############################################################################
  manifests-hasura:
    name: Generate Hasura manifests
    runs-on: ubuntu-latest
    steps:

    - name: Use autodevops manifests generation
      uses: SocialGouv/actions/autodevops-manifests@v1
      with:
        environment: "dev"
        kosko-args: hasura
        koskoChartsVersion: 706effb61a1de4c8e4b48d1a9a987af2e5cd20f5
        rancherId: ${{ secrets.RANCHER_PROJECT_ID }}
        socialgouvBaseDomain: ${{ secrets.SOCIALGOUV_BASE_DOMAIN }}

  # ##############################################################################
  # ## GENERATE KUBERNETES MANIFESTS
  # ##############################################################################
  # manifests:
  #   name: Generate k8s manifests
  #   runs-on: ubuntu-latest
  #   steps:

  #   - name: Use autodevops manifests generation
  #     uses: SocialGouv/actions/autodevops-manifests@v1
  #     with:
  #       environment: "dev"
  #       rancherId: ${{ secrets.RANCHER_PROJECT_ID }}
  #       socialgouvBaseDomain: ${{ secrets.SOCIALGOUV_BASE_DOMAIN }}

  ##############################################################################
  ## DEPLOY HASURA OVER KUBERNETES
  ##############################################################################
  deploy-hasura:
    name: Deploy Hasura
    runs-on: ubuntu-latest
    needs: [create-db, register-hasura, manifests-hasura]
    outputs:
      url: ${{ steps.deploy-hasura.outputs.url }}
    steps:

    - name: Use autodevops deployment
      uses: SocialGouv/actions/autodevops-deploy@v1
      id: deploy-hasura
      with:
        environment: "dev"
        token: ${{ secrets.GITHUB_TOKEN }}
        kubeconfig: ${{ secrets.KUBECONFIG }}
        rancherId: ${{ secrets.RANCHER_PROJECT_ID }}

  ##############################################################################
  ## RESTORE DATABASE
  ##############################################################################
  restore-db:
    name: Restore database
    runs-on: ubuntu-latest
    needs: [deploy-hasura]
    steps:

    - name: Use autodevops database restore
      uses: SocialGouv/actions/autodevops-restore-db@v1
      with:
        kubeconfig: ${{ secrets.KUBECONFIG }}
        rancherId: ${{ secrets.RANCHER_PROJECT_ID }}
        socialgouvBaseDomain: ${{ secrets.SOCIALGOUV_BASE_DOMAIN }}

  ##############################################################################
  ## BUILD AND REGISTER APPLICATION IMAGE
  ##############################################################################
  register-app:
    name: Build & Register application
    runs-on: ubuntu-latest
    needs: [restore-db, deploy-hasura]
    steps:

    - name: Get project name
      run: |
        echo "project=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV

    - name: Use autodevops build and register
      uses: SocialGouv/actions/autodevops-build-register@v1
      with:
        imageName: fabrique/carnets
        project: ${{ env.project }}
        token: ${{ secrets.GITHUB_TOKEN }}
        dockerbuildargs: |
          HASURA_JWT_KEY=${{ secrets.HASURA_JWT_KEY }}
          NEXT_PUBLIC_HASURA_URL=${{ needs.deploy-hasura.outputs.url }}/v1/graphql

  # ##############################################################################
  # ## DEPLOY APPLICATION OVER KUBERNETES
  # ##############################################################################
  # deploy:
  #   name: Deploy application
  #   runs-on: ubuntu-latest
  #   needs: [register, register-hasura, manifests]
  #   steps:

  #   - name: Use autodevops deployment
  #     uses: SocialGouv/actions/autodevops-deploy@v1
  #     with:
  #       environment: "dev"
  #       token: ${{ secrets.GITHUB_TOKEN }}
  #       kubeconfig: ${{ secrets.KUBECONFIG }}
  #       rancherId: ${{ secrets.RANCHER_PROJECT_ID }}

  # ##############################################################################
  # ## RESTORE DATABASE
  # ##############################################################################
  # restore-db:
  #   name: Restore database
  #   runs-on: ubuntu-latest
  #   needs: deploy
  #   steps:

  #   - name: Use autodevops database restore
  #     uses: SocialGouv/actions/autodevops-restore-db@v1
  #     with:
  #       kubeconfig: ${{ secrets.KUBECONFIG }}
  #       rancherId: ${{ secrets.RANCHER_PROJECT_ID }}
  #       socialgouvBaseDomain: ${{ secrets.SOCIALGOUV_BASE_DOMAIN }}

