name: Review

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - v*

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:

  ##############################################################################
  ## BUILD AND REGISTER APPLICATION IMAGE
  ##############################################################################
  register:
    name: Build & Register application
    runs-on: ubuntu-latest
    steps:

    - name: Get project name
      run: |
        echo "project=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV

    - name: Use autodevops build and register
      uses: SocialGouv/actions/autodevops-build-register@master
      with:
        group: "fabrique"
        project: ${{ env.project }}
        token: ${{ secrets.GITHUB_TOKEN }}

  ##############################################################################
  ## BUILD AND REGISTER HASURA IMAGE
  ##############################################################################
  register-hasura:
    name: Build & Register Hasura
    runs-on: ubuntu-latest
    steps:

    - name: Get project name
      run: |
        echo "project=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV

    - name: Use autodevops build and register
      uses: SocialGouv/actions/autodevops-build-register@master
      with:
        image: "hasura"
        group: "fabrique"
        project: ${{ env.project }}
        token: ${{ secrets.GITHUB_TOKEN }}
        dockerfile: ./packages/hasura/Dockerfile

  ##############################################################################
  ## GENERATE KUBERNETES MANIFESTS
  ##############################################################################
  manifests:
    name: Generate k8s manifests
    runs-on: ubuntu-latest
    steps:

    - name: Use autodevops manifests generation
      uses: SocialGouv/actions/autodevops-manifests@master
      with:
        environment: "dev"

  ##############################################################################
  ## DEPLOY APPLICATION OVER KUBERNETES
  ##############################################################################
  deploy:
    name: Deploy application
    runs-on: ubuntu-latest
    needs: [register, register-hasura, manifests]
    steps:

    - name: Use autodevops deployment
      uses: SocialGouv/actions/autodevops-deploy@master
      with:
        environment: "dev"
        token: ${{ secrets.GITHUB_TOKEN }}
        kubeconfig: ${{ secrets.SOCIALGOUV_KUBE_CONFIG_DEV }}

  ##############################################################################
  ## RESTORE DATABASE
  ##############################################################################
  restore-db:
    name: Restore database
    runs-on: ubuntu-latest
    needs: deploy
    steps:

    - name: Use autodevops database restore
      uses: SocialGouv/actions/autodevops-restore-db@master
      with:
        kubeconfig: ${{ secrets.SOCIALGOUV_KUBE_CONFIG_DEV }}
